### ISSUE TITLE
Integrate repo with Snyk

### ISSUE THREAD

**Issue by samithaf** [WestpacGEL/GEL-next#128]
https://docs.snyk.io/

**Comment by jaortiz** [comment]
Having issues importing the project in snyk dashboard. Console is complaining about missing yarn.lock file even though we aren't using it... Have raised a ticket with snyk support.

**Comment by jaortiz** [comment]
Repo is integrated but there may be some features missing due to lack of pnpm support https://docs.snyk.io/scan-using-snyk/supported-languages-and-frameworks/supported-languages-frameworks-and-feature-availability-overview
