### ISSUE TITLE
Accordion component

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#145]
**Colours:**
The text for this component seems to be using the Westpac Brand Text colour (#181b25) regardless of the Theme that is displaying.

**Naming:**
There shouldn't be a 'Primary' version of this component, we have one coloured version in Hero which is called **Lego**
There also shouldn't be a version where you can choose the colour.

**Comment by samithaf** [comment]
@KateMacdonald Please see the latest version and should be fixed now. Please reopen the issue if you still see the issue
