### ISSUE TITLE
Accordion Open and Close Transistion

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#149]
The open and close transition on the Accordion fades the content while the item is opening or closing. This leads to an overlap of content during the animation which is incorrect. See screen grab attached.

The preferred action is to mask the containing content as shown in the current GEL implementation. See screen grab attached.

<img width="1083" alt="Not correct" src="https://github.com/WestpacGEL/GEL-next/assets/936597/1885c7d8-07eb-4a0b-b3c3-d66a75ed8b28">
<img width="1077" alt="Correct" src="https://github.com/WestpacGEL/GEL-next/assets/936597/c8c52684-bff4-4ccc-97b8-93f4e335e597">

**Comment by samithaf** [comment]
@justinspencer please retest and open the issue if it's still not fixed.

**Comment by samithaf** [comment]
@jaortiz I just reopened the original issue.
