### ISSUE TITLE
Alert text wrapping and icon clipping

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#150]
In XS the text is not wrapping correctly and (in Safari) the top of the icon is clipping. (See screen grab attached)
Please see current GEL application for correct implementation. Also if possible please provide examples with more content as this will ensure that we can test for these scenarios.
<img width="372" alt="Alert xs" src="https://github.com/WestpacGEL/GEL-next/assets/936597/b31ca2bc-2147-481d-9a7b-c331b9db7fdf">

**Comment by samithaf** [comment]
@justinspencer Please try to use the control panel to modify the component content and might satisfy your requirement. Let us know if it is not the case, so we can add more examples.

![Screenshot 2023-10-18 at 4 00 56 pm](https://github.com/WestpacGEL/GEL-next/assets/1860417/d9d22edb-a829-4ea7-8007-c023a26cba70)

**Comment by justinspencer** [comment]
Will do thanks Samitha.

**Comment by samithaf** [comment]
@justinspencer please test the icon position again and should be fixed now.
