### ISSUE TITLE
Autocomplete No Options display and icon rendering

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#151]
1. The "No Options" prompt is not displayed as per the current GEL. See screen grab attached.
2. I'm noticing rendering issues with the icons. The icon in the error message should be 12px. It's drawn on the pixel grid so it should be super sharp and not distorted as shown in the screen grab attached. Note: this also happens in the current GEL. Chrome and Safari.

<img width="969" alt="Autocomplete no no opions" src="https://github.com/WestpacGEL/GEL-next/assets/936597/6ee773be-76fb-457b-81ce-ad1c8f046ae3">
<img width="826" alt="Autocomplete icon issue" src="https://github.com/WestpacGEL/GEL-next/assets/936597/75b1e0ac-9f13-46f3-a44a-0db1d88f29c9">
<img width="969" alt="Autocomplete no options" src="https://github.com/WestpacGEL/GEL-next/assets/936597/0e3a7d6f-433f-4499-87de-c32e8291ed23">

**Comment by samithaf** [comment]
@justinspencer yeah something funny going on with icons for sure. "no options" is simply a implementation of the component consumer but we can add an e.g. for sure. cc. @tomjackking

**Comment by justinspencer** [comment]
All good. Regarding the "no options" feature I'd check with @KateMacdonald as this is more of a UX decision.

**Comment by samithaf** [comment]
I just checked how Mesh version interaction and it has a strange behaviour :|

![Screenshot 2023-10-18 at 9 26 13 pm](https://github.com/WestpacGEL/GEL-next/assets/1860417/fbd03e60-6f9f-473e-aef9-5032dd239450)
