### ISSUE TITLE
Form - Alert message icons

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#152]
Theres something going wrong with these icons. See screen grab attached.  I suspect they are being scaled incorrectly. See current GEL for correct rendering. Please note: Icon sizes must always be either 12, 18, 24, 36 or 48px. See link below for more information:
https://gel.westpacgroup.com.au/design-system/foundation/icons?b=WBC

<img width="653" alt="1  Error message icon NEXT" src="https://github.com/WestpacGEL/GEL-next/assets/936597/05e6e511-d5ee-4053-97bb-54cb79675a76">
<img width="978" alt="2  Error message icon GEL" src="https://github.com/WestpacGEL/GEL-next/assets/936597/1f0357e3-a8ea-45c2-8031-e7e6acb6dca0">

**Comment by samithaf** [comment]
@justinspencer we published a fix for the icon issue and please have a look. https://gel-next-storybook.vercel.app Also icon clip issue should be fixed in Safari. Thanks @tomjackking for the quick fix! 

Please feel free to reopen the issue if it's still not fixed.
