### ISSUE TITLE
ButtonDropdown Block text and carrot alignment

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#154]
In the ButtonDropdown Block the text should be aligned to the left and the carrot should be aligned to the right. See current GEL. I've also attached screengrabs.

<img width="934" alt="Button dropdown block correct" src="https://github.com/WestpacGEL/GEL-next/assets/936597/ec4cc346-e904-4ee4-b87e-1db43edd38ab">

<img width="929" alt="Button dropdown block not correct" src="https://github.com/WestpacGEL/GEL-next/assets/936597/ec21c8cf-003b-4140-8024-30e584d46c9d">

**Comment by samithaf** [comment]
@justinspencer please test again and it's fixed now.
