### ISSUE TITLE
Button  - As Link

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#157]
Not sure if I'm doing something wrong but example doesn't look like it has button link styling applied.

<img width="655" alt="Not Button Link Styling" src="https://github.com/WestpacGEL/GEL-next/assets/936597/f524af45-4660-44a4-8128-1077d7ad40d0">

**Comment by samithaf** [comment]
@justinspencer "As Link" shows developers, they can use that option to render an `anchor tag` instead of `button tag` Link styling of the button is in here, https://gel-next-storybook.vercel.app/?path=/story/components-button--colors 

Please reopen this issue in case if we are missing something.

**Comment by justinspencer** [comment]
All good. Thanks.
