### ISSUE TITLE
Checkbox group - Selected tick

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#159]
The tick in GEL-next is too thick and doesn't match the tick in the current GEL. FYI. It would be good to reduce the weight of these ticks to better match the icon style. Let me know if this is possible and I'll provide a design.

<img width="407" alt="Next - Not correct" src="https://github.com/WestpacGEL/GEL-next/assets/936597/84726b9b-1359-49a6-b05a-e3e64301ea63">
<img width="540" alt="GEL - Correct" src="https://github.com/WestpacGEL/GEL-next/assets/936597/88ab400d-f002-411d-9218-8cbf80245246">

**Comment by samithaf** [comment]
@justinspencer looks like current version of the GEL is not using a SVG for tick instead depend on CSS. 

However new GEL is using a SVG and can be updated easily. Please provide a SVG and we can update the component.

**Comment by justinspencer** [comment]
@tomjackking I've attached svgs for both default size and large. Note: these svgs include the border. Let me know if this is not correct and I'll provide the tick only.

![Checkbox Selected Default](https://github.com/WestpacGEL/GEL-next/assets/936597/5bb407b1-dc83-41d4-8f84-11acae7e5e1b)
![Checkbox Selected Large](https://github.com/WestpacGEL/GEL-next/assets/936597/316225e4-4c61-46df-ba97-7b5dedfc5165)

**Comment by tomjackking** [comment]
@justinspencer if you can just provide the tick only that would be perfect.

**Comment by justinspencer** [comment]
@tomjackking Here they are. As discussed to ensure the correct positioning I've done them in the bounding box. (24px default and 30px large).

[Checkbox svgs.zip](https://github.com/WestpacGEL/GEL-next/files/13065005/Checkbox.svgs.zip)

**Comment by samithaf** [comment]
@justinspencer please check the latest. @tomjackking added the provided SVG's
