### ISSUE TITLE
Checkbox group - focus state displayed on a mouse event

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#160]
In the original GEL Dom added a small piece of JavaScript to ensure that the browser focus state was only rendered when the using the keyboard. I'm not sure if a decision has been reversed however the current GEL still seems to implement it.

<img width="639" alt="Checkbox focus state" src="https://github.com/WestpacGEL/GEL-next/assets/936597/450a9247-a7fd-4053-a974-430925b1030f">

**Comment by samithaf** [comment]
@justinspencer I can see the focus ring on mouse click event in current GEL. Am I missing something?

https://westpacgel.netlify.app/form-check/size

**Comment by justinspencer** [comment]
I'm testing in Safari which is doing what it's supposed to do ie. Not showing the focus state when the user is using the mouse.

**Comment by tomjackking** [comment]
More info and follow up to be found in #310 closing this issue
