### ISSUE TITLE
Input field with Search icon and clear button

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#173]
Currently uses the close icon and should probably use the clear icon.

<img width="669" alt="Input wrong icon" src="https://github.com/WestpacGEL/GEL-next/assets/936597/650cf927-9d23-4cbf-883a-ba5eee6737da">

**Comment by samithaf** [comment]
@tomjackking let's update the docs; https://westpacgel.netlify.app/input-field/scenarios
