### ISSUE TITLE
Input field icon colours

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#174]
Out of the box I think all icons in input fields should be Muted. @KateMacdonald is this correct?

On another note... Do icons in Input fields have colour options and what are the UX rules around clickable vs none clickable icons?

<img width="879" alt="Input icon colours" src="https://github.com/WestpacGEL/GEL-next/assets/936597/6188f77b-61b4-409e-95c6-7578d77994f9">

**Comment by samithaf** [comment]
@justinspencer from developer point of view, component accept any `Icon component` and `colour` can be configured as well.
