### ISSUE TITLE
Pagination arrows moving

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#175]
I'm not aware of the use-cases for this component however, Ideally the arrows shouldn't move when clicked. See movie attached.

https://github.com/WestpacGEL/GEL-next/assets/936597/f11214e6-21d0-459d-a5d0-b211266f0bf4

**Comment by samithaf** [comment]
Yeah seems like a bug for me. Looking at current version it's not moving https://westpacgel.netlify.app/pagination/usePagination

**Comment by justinspencer** [comment]
@KateMacdonald I'm not sure what the use case is for this component. Please could you check to see if it will cater to the requirements.
