### ISSUE TITLE
The GRID

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#184]
Not sure what's going on here but it's not how the grid works.

Every break point has a specific gutter width and margins. When the grid (columns) reach a max width of 1200px the grid is set to a fixed width and centred in the viewport.

The best demonstration of the GRID is the one we created in GUI 2.0 (See link below). However, please note the margins have increased in Xs since we did this and we've also added the Xsl breakpoint.  I've attached a video showing how the grid responds to different viewport sizes.

https://gel.westpacgroup.com.au/GUI/WBC/templates/

<img width="962" alt="Screenshot 2023-10-24 at 12 43 37 pm" src="https://github.com/WestpacGEL/GEL-next/assets/936597/795654a5-c5f5-4c9b-b126-b890b846d5a9">

https://github.com/WestpacGEL/GEL-next/assets/936597/bbd548bc-bea9-4999-9bdb-9f4e03efa881

**Comment by jaortiz** [comment]
@justinspencer I've updated the demo to properly reflect how the grid works. https://gel-next-storybook-git-fix-grid-demo-westpacgel.vercel.app/?path=/story/foundation-grid--default-container Let me know if this is working correctly.

**Comment by justinspencer** [comment]
@jaortiz  I've attached 3 issues that I can see.

1. 24px padding around the grid in all views. This is causing the grid to display incorrectly.
2. In Xsl the gutter width should be 18px.
3. In Xs the margin has increased to 24px.

Here' a link to the Grid Figma dev file. It shows the grid at all breakpoints in templates with and without a sidebar.
https://www.figma.com/file/ZklhkklQAfRVkvZ6xwmzZr/GEL-Responsive-Grid?type=design&node-id=345%3A11102&mode=dev

<img width="1086" alt="1 Grid - strange padding" src="https://github.com/WestpacGEL/GEL-next/assets/936597/63b6161b-6163-4617-85b7-8f6ad400580d">

<img width="1082" alt="2 Grid - Xsl gutter width " src="https://github.com/WestpacGEL/GEL-next/assets/936597/7517ef72-e033-4940-81e3-4dad89fcbb19">

<img width="1080" alt="3 Grid - Xs margin" src="https://github.com/WestpacGEL/GEL-next/assets/936597/6e0746c7-b0e1-4c4a-bb2b-babaca619095">

**Comment by jaortiz** [comment]
@justinspencer fixed https://gel-next-develop-storybook.vercel.app/?path=/story/foundation-grid--default-container

**Comment by justinspencer** [comment]
@jaortiz Awesome thanks. I'm assuming this will be replace what's in the main site?
