### ISSUE TITLE
Logos as UI icons

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#185]
Logos and Symbols etc must not be added to the GEL icon library. This is for various reasons including brand specifications, accessibility requirements and overall consistency.

The link below details the design principles and usage guidelines for UI icons.
https://gel.westpacgroup.com.au/articles/iconography

<img width="810" alt="Icons only" src="https://github.com/WestpacGEL/GEL-next/assets/936597/c56295a7-ac89-409b-8f24-b207e1682a39">

**Comment by jaortiz** [comment]
@justinspencer removed https://gel-next-storybook.vercel.app/?path=/story/foundation-icons--default
