### ISSUE TITLE
Logos missing

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#187]
There are a lot of multi-brand logos missing. Please see the current GEL. Note. These logos are created specifically for use in multi-brand applications. They ensure that the correct logo is used at the correct size and in the correct position with zero dev effort. Each logo variation is crafted to fit into the container and where possible align with the pixel grid in order to ensure the best possible rendering quality. Allowing (or relying) on designers and developers to scale and position these logos correctly proved to be problematic.

<img width="1209" alt="Logos missing" src="https://github.com/WestpacGEL/GEL-next/assets/936597/17ca9319-f775-48b7-93ac-a6e4ebc57f7d">

<img width="689" alt="GEL Multi-brand logos" src="https://github.com/WestpacGEL/GEL-next/assets/936597/95fff9a9-8d46-4ba6-83b4-36f2c2a15e22">

**Comment by jaortiz** [comment]
@justinspencer fixed https://gel-next-storybook.vercel.app/?path=/story/foundation-symbols--all-logos
