### ISSUE TITLE
Icons that need to be updated/added

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#188]
These have been in our backlog for a while. I've linked to the Trello cards below:

https://trello.com/c/hy0i0UEu

https://trello.com/c/Fg3dTgM1

https://trello.com/c/KNIsVrG4

**Comment by jaortiz** [comment]
@justinspencer added. https://gel-next-storybook.vercel.app/?path=/docs/foundation-icons--docs
