### ISSUE TITLE
Focus colour

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#192]
The focus colour should not be part of the Primary UI palette. If anything it's a reserved colour however I would also argue that it does not need to be exposed. Not sure if this is possible in Storybook so I'd tend to put it in the reserved colours.

<img width="1448" alt="Colours Focus" src="https://github.com/WestpacGEL/GEL-next/assets/936597/58a4d595-7b2c-4630-90a0-7c230dd91b96">

**Comment by samithaf** [comment]
@justinspencer we literally followed the logical grouping of Mesh version. But we can simply update it.

![Screenshot 2023-10-24 at 4 40 12 pm](https://github.com/WestpacGEL/GEL-next/assets/1860417/06079272-3389-4bdf-ab91-751a2d0c8a3b)

**Comment by totaland** [comment]
@justinspencer @samithaf after a quick discussion with Justin this will be the solution going forward. The focus colour will be hidden in storybook.
<img width="2269" alt="image" src="https://github.com/WestpacGEL/GEL-next/assets/36496259/f36ef420-cb00-4f84-9cf3-7a282ee58d53">

**Comment by samithaf** [comment]
@totaland for the fix. @justinspencer please change will be available later today.
