### ISSUE TITLE
Typography Font weights

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#194]
I'm guessing this is a token thing but we also need to provide font weights.

We currently use numerical values to assign different font weights;
Light 300
Regular 400
Medium 500
Semi-bold 600
Bold 700
Heavy 800

This works well with body fonts as our system fonts SF, Roboto and Segoe map to these weights perfectly. With brand (web) fonts we have to map these weights to specific fonts. See BOM brand (link below) that uses LL Brown web font in 3 different weights. Each weight is a different font.
https://gel.westpacgroup.com.au/design-system/foundation/fonts?b=BOM
BSA is a similar scenario.

**Comment by samithaf** [comment]
@justinspencer it's a purely a documentation gap but we do have the weights as tokens. We will update the docs. Thanks

**Comment by totaland** [comment]
<img width="1376" alt="image" src="https://github.com/WestpacGEL/GEL-next/assets/36496259/de492195-4b90-49da-852c-4e01403f9f11">
Add storybook to document how to use font weight

**Comment by totaland** [comment]
@justinspencer this should have different font family for different brand. 
<img width="1407" alt="image" src="https://github.com/WestpacGEL/GEL-next/assets/36496259/356f01f7-3919-4c6d-8237-45178f9a6bf6">

**Comment by justinspencer** [comment]
@samithaf Just to clarify my conversation with James. BOM and BSA use multiple weights for their brand fonts. These web fonts have to be mapped to the respective numerical values. See links below:
https://gel.westpacgroup.com.au/design-system/foundation/fonts?b=BOM
https://gel.westpacgroup.com.au/design-system/foundation/fonts?b=BOM
These are not currently shown in the GEL Next Storybook.

**Comment by samithaf** [comment]
Hey @justinspencer, we updated the stories and added two separated tables for font weight ( body and brand ). Please have a look, https://gel-next-storybook.vercel.app/?path=/docs/foundation-typography--docs

**Comment by justinspencer** [comment]
Can you please confirm that the numerical weights have been mapped to the actual webfont. For example BOM uses the following web fonts: Brown Light, Brown Regular and Brown Bold. Also note: STG and WBC do not use different weights for their brand fonts and we should never force faux bold or bad things will happen. Happy to chat if this is confusing.

<img width="1023" alt="Faux Bold WBC" src="https://github.com/WestpacGEL/GEL-next/assets/936597/58293ae4-d811-425f-b4ab-d82d7087db0b">


<img width="1021" alt="Faux Bold STG" src="https://github.com/WestpacGEL/GEL-next/assets/936597/c3e2cfff-3237-411f-b0b1-e5c8b3d7de44">

**Comment by samithaf** [comment]
@jaortiz please have a chat with @justinspencer

**Comment by jaortiz** [comment]
@justinspencer fixed here https://gel-next-develop-storybook.vercel.app/?path=/story/foundation-typography--brand-font-weight
