### ISSUE TITLE
Pagination borders

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#195]
The borders should not be visible on the selected state. See attached. Also see current GEL.

<img width="755" alt="Pagination incorrect" src="https://github.com/WestpacGEL/GEL-next/assets/936597/88ed71d3-1b96-4c52-b615-31152f3a1631">

<img width="755" alt="Pagination incorrect" src="https://github.com/WestpacGEL/GEL-next/assets/936597/20239f34-3ea1-47f0-8d0b-a6c257c3e15d">

**Comment by jaortiz** [comment]
@justinspencer Fixed here https://gel-next-storybook.vercel.app/?path=/story/components-pagination--default
