### ISSUE TITLE
Exit icon is not rendering correctly

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#210]
For some reason it's being clipped at the bottom.
<img width="165" alt="Screenshot 2023-10-26 at 5 22 10 pm" src="https://github.com/WestpacGEL/GEL-next/assets/936597/8205462f-febc-445d-bc4b-eafbe756cfeb">

**Comment by jaortiz** [comment]
@justinspencer the ExitIcon you provided is built to use a viewBox of "0 0 24 25" but in code we use a default viewbox of "0 0 24 24" (as all icons currently use this) which is causing the clipping. Are you able to provide an updated icon within this viewBox

**Comment by justinspencer** [comment]
That's a worry.

I've attached new exports.

![exit-outlined](https://github.com/WestpacGEL/GEL-next/assets/936597/4db1e752-6612-479e-b5c5-8b18d41374da)
![exit-filled](https://github.com/WestpacGEL/GEL-next/assets/936597/eac4faf8-4595-484b-b70d-08b475d00498)
