### ISSUE TITLE
The Grid Breakpoints

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#220]
GEL Next seems to have different breakpoints to current GEL. Please match current GEL breakpoints, gutters, margins etc.

The GEL breakpoints are:
**Xs:** 0px - 575px
**Xsl:** 576px - 767px
**Sm:** 768px - 991px
**Md:** 992px - 1199px
**Lg:** 1200px

**Comment by samithaf** [comment]
@justinspencer GEL Next and current GEL got exactly the same breakpoints. 

This is current GEL https://github.com/WestpacGEL/GEL/blob/master/brands/WBC/tokens/layout.js

This is GEL Next https://github.com/WestpacGEL/GEL-next/blob/main/packages/ui/src/tailwind/constants/breakpoints.ts

Have you noticed any difference?

**Comment by justinspencer** [comment]
@samithaf Not sure what you mean. Happy to do a call when you're free.

**Comment by samithaf** [comment]
@justinspencer happy to have a call but I think I got what you are saying. You are referring grid breakpoints and I was referring to breakpoints available outside of the grid. @jaortiz working on https://github.com/WestpacGEL/GEL-next/issues/184 and I believe it's related.
