### ISSUE TITLE
Hover state on accordion is missing.

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#232]
In GEL to the accordion used to have a hover state (see link below). This matched the hover state of the tabs. Not sure why but it was not implemented in GEL 3.0. Would be good to get this back in at some stage.

https://gel.westpacgroup.com.au/GUI/WBC/containers/

<img width="771" alt="No hover state" src="https://github.com/WestpacGEL/GEL-next/assets/936597/b53d8f3d-b9f9-4eb7-ab9e-822d378519d0">

**Comment by samithaf** [comment]
@justinspencer fixed please check the latest version

**Comment by justinspencer** [comment]
@samithaf Sorry, the hover state should be animated to match the hover state of the tabs.
