### ISSUE TITLE
Date Picker -  current day

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#252]
Current day highlight has to have primary border for accessibility. See current GEL

<img width="1099" alt="Date-picker wrong" src="https://github.com/WestpacGEL/GEL-next/assets/936597/f360c448-4a73-48c7-a21b-535a8a2158c7">

<img width="1093" alt="Date-picker right" src="https://github.com/WestpacGEL/GEL-next/assets/936597/cae2f9b2-677c-425d-ac9a-1824520dc25f">

**Comment by samithaf** [comment]
@justinspencer Fixed. please check the latest version.
