### ISSUE TITLE
Webfont distribution and Licence

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#257]
This is just a heads up regarding distribution of Webfonts.

We have licences to use each of our Webfonts on specific domains and in certain apps. These licences permit us to host the fonts on our servers, however when it comes to providing access to the actual webfont files (via a download link) this must be behind the firewall as the licence agreements do not permit us to freely distribute the web fonts. GEL currently directs developers to Sharepoint in order to download the webfont files and I'd recommend keeping this process in place.

More info here:

https://gel.westpacgroup.com.au/articles/typography
https://gel.westpacgroup.com.au/articles/using-fonts

**Comment by samithaf** [comment]
cc @kenjishiromajp @jaortiz

**Comment by samithaf** [comment]
We will be deep linking in to exisiting font location.
