### ISSUE TITLE
Flexi Cell

### ISSUE THREAD

**Issue by samithaf** [WestpacGEL/GEL-next#265]
Looks like Tailwind normaliser styles impacting FlexiCell component and also looks like some of the styles are not compatible with the original design. Please double check original Figma design

**Comment by KateMacdonald** [comment]
All the Text is correct, as is the icon that appears on the right. However it looks like the icons and symbols that appear on the Left are still getting larger as the breakpoint changes, they also need to stay the same size. Ie the flag, circle, icon.

**Comment by tomjackking** [comment]
> All the Text is correct, as is the icon that appears on the right. However it looks like the icons and symbols that appear on the Left are still getting larger as the breakpoint changes, they also need to stay the same size. Ie the flag, circle, icon.

As discussed outside github this was just for example purposes and examples will be updated to reflect more default sizing

**Comment by KateMacdonald** [comment]
When there is no border - there shouldn't be any left or right padding. That is a specification error from the original designs on my part. 
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/c9b022a0-8829-438e-a169-b334ea1c14e2)

**Comment by KateMacdonald** [comment]
I have reviewed this and all the changes have been made (Thanks Tom), I have updated the status of the Design review in Confluence.
