### ISSUE TITLE
GEL site action bar correct logo hover state

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#273]
This bug was a bug previously raised in our Trello board but due to time and resources we were not able to get it fixed.

The intended transition for the hover state on the brand icons is shown in the video attached. Note how the mouse-over transition is slightly longer than the mouse-out transition. Also note that this also applies to the icons in the footer.

This was proving difficult to achieve in Chrome which seemed to be re-positioning the icons as the stoke got thicker. So as a quick fix the transition was removed. It would be good to apply this transition to match the rest of the interactions in the site. If the Chrome issue continues to cause issues then I'm happy to use  border-box on the stroke so the dimensions do not change.

https://github.com/WestpacGEL/GEL-next/assets/936597/26c8be84-0af7-4e6a-aa54-e3366cd1fa38

**Comment by kenjishiromajp** [comment]
@justinspencer  I believe the video is corrupted or something, since it is not playing on my personal laptop and the working laptop

**Comment by justinspencer** [comment]
@kenjishiromajp I've uploaded it to Vimeo. Here's the link:

https://vimeo.com/885023624/1cea7a0c9e?share=copy
