### ISSUE TITLE
Compacta - Text clipping

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#286]
The text is clipped when the item is open and closed. Safari.

<img width="1126" alt="Compacta clipping text" src="https://github.com/WestpacGEL/GEL-next/assets/936597/b7fcb3a3-14c8-4044-944d-ddbc5231d3da">

**Comment by samithaf** [comment]
@justinspencer Can you check the latest version? We retested on Safari in two seperate machines and we can't replicate.

**Comment by justinspencer** [comment]
@samithaf I think it must be a browser bug. I can replicate the issue but it's sporadic and as soon as I resize the browser window it fixes.

**Comment by KateMacdonald** [comment]
I tried to re-create as well, but couldn't.
