### ISSUE TITLE
Placeholder text for BOM and STG

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#288]
Note: This is an issue with the current GEL too. I'm not sure how the colour of placeholder text is defined but it should probably use a grey (neutral) tint rather than a colour.

<img width="624" alt="Placeholder text STG" src="https://github.com/WestpacGEL/GEL-next/assets/936597/3d423d3a-c8bb-4f89-a29d-40f80be13c8c">

<img width="623" alt="Placeholder text BOM" src="https://github.com/WestpacGEL/GEL-next/assets/936597/ed6656ae-7ff0-4370-8532-241b450700ea">

**Comment by kenjishiromajp** [comment]
Hey @justinspencer which grey color should we use? is border-50 a good choice?

**Comment by justinspencer** [comment]
Hey @kenjishiromajp. Do the other brands use border-50?

**Comment by justinspencer** [comment]
Update. I've just had a chat with Kate and we think that placeholder text should not be used. We've had a lot of discussion regarding this in the past. Designers love it but Accessibility does not.

**Comment by kenjishiromajp** [comment]
so can I close this issue then? @justinspencer

**Comment by justinspencer** [comment]
@kenjishiromajp Yep all good. We just need to make sure that inputs do not use placeholder text.
