### ISSUE TITLE
GEL Site hover not working in Safari.

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#303]
The hover state on the Home Screen isn't working properly in Safari. See screen recording attached.

https://github.com/WestpacGEL/GEL-next/assets/936597/b53c50b6-0868-4706-a487-28bc16b3e3e1

**Comment by KateMacdonald** [comment]
This is an issue with Safari that can't be fixed by us - may be resolved in a future Safari release.
