### ISSUE TITLE
Focus state when using the mouse/tapping

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#310]
I'm going to add this as a separate issue as it relates to all components.

Ideally we don't want the focus state to be visible when the user is interacting with the mouse or tapping on a touch device. The focus state should only be visible when the user is interacting with the keyboard. In the current GEL system, only text inputs receive a visible focus state when they receive focus. Some examples where GEL Next is using focus and should not be are:

- [ ] 1. Radio
- [ ] 2. Checkbox
- [ ] 3. Selector
- [ ] 4. GEL site dropdown and dropdown items

**Comment by samithaf** [comment]
@justinspencer we can see the focus ring in current GEL version in the production for following components. GEL site dropdown doesn't have the focus ring in current production.

1. Radio - https://westpacgel.netlify.app/form-check/size
2. Checkbox - https://westpacgel.netlify.app/form-check/size
3. Selector - https://westpacgel.netlify.app/selector/examples

**Comment by samithaf** [comment]
Ok, now I get the confusion. Current GEL shows a focus ring on Chrome but not in Safari. New GEL shows focus ring on all the browsers in above components.

**Comment by justinspencer** [comment]
Yeah I think I'm the only person testing in Safari but as it's the iOS browser I figured it's probably a good idea.

**Comment by samithaf** [comment]
@justinspencer looks like focus ring is visible current production GEL select component on mouse click ( Safari ). Is this as design or a bug? I am quoting your feedback "_In the current GEL system, only text inputs receive a visible focus state when they receive focus._ "

![Screenshot 2023-11-21 at 4 39 42 pm](https://github.com/WestpacGEL/GEL-next/assets/1860417/19f1d4bc-43a0-48a4-80b3-f61973cc5556)

**Comment by justinspencer** [comment]
Hi Samitha, Apologies for the confusion. I've discussed this with the team and I've also reached out to Julie our accessibility consultant. Ideally we would like to hide the focus state on all components unless the user is navigating using a keyboard.

We used to do this with JavaScript however, according to Julie there's a better way. Here is her response:

There is now a CSS selector called [:focus-visible](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdeveloper.mozilla.org%2Fen-US%2Fdocs%2FWeb%2FCSS%2F%3Afocus-visible&data=05%7C01%7Cjspencer%40westpac.com.au%7C3a666a1552d64c66eb7608dbea5202b9%7C57c64fd466ca49f5ab382e67ef58e724%7C0%7C0%7C638361410181143793%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BVkk3cR0Wkk%2Bd9Tg2eAAe7Km8igkDKHLPpsdY9oiWmM%3D&reserved=0) and it doesn’t apply to mouse or touch inputs. :

To be 100% certain that you’re always meeting WCAG 2.2, you should use one of the fallback methods which are at the end of this post about [focus-visible and backwards compatibility](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.tpgi.com%2Ffocus-visible-and-backwards-compatibility%2F&data=05%7C01%7Cjspencer%40westpac.com.au%7C3a666a1552d64c66eb7608dbea5202b9%7C57c64fd466ca49f5ab382e67ef58e724%7C0%7C0%7C638361410181143793%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QAdwYVjhtANn5mByFaL3zwMyp4r0x%2BFFZzLb62xQHM8%3D&reserved=0). Look for the heading ‘Support notes – March 2023’ for some code samples you can copy-paste. You can ignore everything before that as it is now out of date.

I think you should be able to put a focus-visible style (with a fallback) at the base level of your CSS, not tied to any particular component or element. Then you can remove any of the existing focus styles that aren’t needed anymore. And if there are little exceptions where you want additional or different focus styles, it will be easy to override the focus-visible just for that component.

Hope this helps!
Julie

**Comment by samithaf** [comment]
cc. @tomjackking
