### ISSUE TITLE
GEL Article - Margin bottom in XS

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#328]
In XS bottom margins should be reduced. Please match margins and spacing as shown in current GEL. See example below.

<img width="472" alt="article margin bottom" src="https://github.com/WestpacGEL/GEL-next/assets/936597/efbd8df4-d825-4c22-bcae-e00feedc36d3">

**Comment by samithaf** [comment]
@justinspencer fix is available in the latest version.
