### ISSUE TITLE
GEL Article - Footer space

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#329]
In the absence of the footer that we were hoping to implement here please increase the space between the sticky footer and the end of the content to match current GEL. See attached.

<img width="1476" alt="article footer margin" src="https://github.com/WestpacGEL/GEL-next/assets/936597/56c16f26-ec47-4491-9493-0c8ba3a57c84">

**Comment by samithaf** [comment]
@justinspencer I highly doubt space gap between footer and article content is a standard unit across articles. If you see following two articles space is different. Looking at the code, space is managed by random spaces via cms in the current GEL. We can match it to a standard unit if you want.

- /articles/value-of-a-design-system
- /articles/code-with-GEL
