### ISSUE TITLE
GEL Article numbered list indent

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#378]
Please align the numbered list with the grid/body text and reduce the text indent to match current GEL.

See screen grab attached.

<img width="1320" alt="GEL Article numberd list" src="https://github.com/WestpacGEL/GEL-next/assets/936597/6c7d2c02-b00a-4c6e-985c-d77a05e533ae">

**Comment by tomjackking** [comment]
A note for this issue to make sure when updating the list to fit this screen it also looks correct in component pages (for example Table)
