### ISSUE TITLE
Design system docs - Dividers on the code tab not full width

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#459]
Some of the dividers on the code tab page content are not stretching the full width of the page, seems ok on on other tabs.

![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/a0517a6d-2896-4f6a-ae4d-7027a7ab2913)

**Comment by tomjackking** [comment]
Just an update, those dividers shouldn't be there going off old site. They will be removed, will check other pages to see if they are there when they shouldn't be

**Comment by KateMacdonald** [comment]
@tomjackking Hey Tom, do you know if the CMS has the option for the divider to be either full width or short? or is there only one style?

**Comment by tomjackking** [comment]
@KateMacdonald there is only one style from what I can see

**Comment by KateMacdonald** [comment]
So the only style available is full-width?

**Comment by tomjackking** [comment]
There is a couple of different ways the divider can get rendered one will display like above and one will go all the way across the screen if there are sections. I'm going to get one of the others to have a look at this

**Comment by KateMacdonald** [comment]
@tomjackking Awesome, thank you. In the current GEL the different divider styles are different colours, it would be great if they were both border colour in the new site.
