### ISSUE TITLE
Design system docs - Blue code panel styling

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#461]
GEL4
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/1085d2b0-c40d-4ae0-a213-9afa49588a8d)

Original GEL
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/da8c9116-8027-43c8-8a11-8387b4a504f8)

Install and Usage copy is **Black** in the GEL4, the old version has it as **Hero** - it should really be **Info blue** like the rest of the panel.

Also not sure why is has a white highlight - is that a code thing??

**Comment by samithaf** [comment]
White highlight text is something people copy & paste

**Comment by samithaf** [comment]
@KateMacdonald fixed. Please test in latest version.
