### ISSUE TITLE
Design system docs: Shadow appearing when menu becomes 'off-canvas'

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#463]
When the menu becomes 'off-canvas', a gradient shadow appears down the left hand side of the page.

**GEL4**
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/3feaced0-f29a-43ce-ad84-f5d4a63596d9)
**Original GEL**
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/ffeb1fea-e366-4cdf-9b98-cda57f88b401)

**Comment by samithaf** [comment]
@KateMacdonald fixed in the latest and please retest.
