### ISSUE TITLE
Design system docs: H2 Padding 

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#465]
All H2 heading styles should have 42px padding below for Sm+ views, and 24px padding for Xs.

**GEL4** Sm+
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/b62983a7-c39e-405c-9c94-bd6cf1e68648)

**Original GEL** Sm+
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/62fb42c7-181e-4375-a7a6-1ef43f4f32f1)

**GEL4** Xs
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/d0313e9b-e49d-4903-8d0f-74a69005b955)
**Original GEL** Xs
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/ffeca399-1e88-4867-b063-d63de7846263)

**Comment by samithaf** [comment]
@KateMacdonald fixed in the latest version. Please reset.
