### ISSUE TITLE
Design system docs - Narrow images should be side-by-side, not stacked

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#470]
**Original GEL**
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/b7ced196-8613-4ca5-b157-eeacf9f394b1)

**GEL4**
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/942aeae3-a3ad-4f63-a7b1-3957cb7b3152)

**Comment by samithaf** [comment]
@KateMacdonald fixed.
