### ISSUE TITLE
Design system docs - white gap at the bottom of short pages

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#472]
When the content of the page is short there appears to be a white gap at the bottom.

**Original GEL**
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/7a83780a-8d77-4856-ad00-d9412e58381e)

**GEL4**
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/457011ab-06a0-47e0-9ca8-3a0a76bab7f8)

**Comment by KateMacdonald** [comment]
Just noticed that on original GEL, there is no footer on these short pages, there should be.

**Comment by samithaf** [comment]
@KateMacdonald this is fixed now and please check in latest version.
