### ISSUE TITLE
Design system docs - Colour impairment demo spacing

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#479]
The gap between the 'Select filter' box and the demo should be 24px (is currently 48px.

**Original GEL**
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/ebcfe68e-749f-4f86-a2bd-893e86284389)

**GEL4**
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/2cb6189f-e62f-4c66-9980-a2da64136fd4)

**Comment by samithaf** [comment]
@KateMacdonald fixed now. Please re-test.
