### ISSUE TITLE
Copy change: GEL article site home - Footer: "BankSA" and "RAMS"

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#494]
Change the the copy for Rams and Bank SA to be: RAMS and BanksSA 

<img width="383" alt="Screenshot 2023-12-07 at 3 15 31 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/8c2556a4-9285-409a-b49e-ca796a39c633">

(The old site was incorrect: It should have had these titles)

**Comment by jaortiz** [comment]
Fixed in #497
