### ISSUE TITLE
Design System Docs: Colour Vision Impairments - Page content links are missing

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#495]
Please add as per the image from the old site:

Old site:
<img width="332" alt="Screenshot 2023-12-08 at 12 18 43 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/a8a07ca3-883d-4b4e-a740-66a332e7143b">

GEL 4.0:
<img width="331" alt="Screenshot 2023-12-08 at 12 18 39 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/e7748990-aab3-41b9-96c1-a949e7b29a8a">

https://gel-next-site.vercel.app/design-system/accessibility/colour-vision-impairment?brand=wbc

**Comment by KateMacdonald** [comment]
@catalinacatalina This is fine I will close
