### ISSUE TITLE
Design System Docs: Colour Vision Impairments – Heading is displaying after the first paragraph - move heading to top of the article

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#496]
Old Site:
<img width="694" alt="Screenshot 2023-12-08 at 12 21 49 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/f9a53e53-408f-47b6-aca9-3507f6d7f0aa">

New site:
<img width="845" alt="Screenshot 2023-12-08 at 12 21 55 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/d3ba1a3a-3523-469d-a96e-12aef40d9e7a">

**Comment by samithaf** [comment]
Every other page start with a Title except this page. Can we rewrite the content to be consistent with pattern established in GEL design system pages? This will reduce unwanted complexity of CMS setup. cc. @KateMacdonald @catalinacatalina

**Comment by KateMacdonald** [comment]
@catalinacatalina This is fine I will close.
