### ISSUE TITLE
Design System Docs: Colour Vision Impairments – Reduce the size of the sub-headings within the sections

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#498]
Sub-heading size within the sections should be smaller than the Heading for the section.  

Old:
<img width="716" alt="Screenshot 2023-12-08 at 12 23 07 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/5bb8d469-6cbf-4e65-a5b6-6c91e24cd07d">

GEL 4.0:

<img width="814" alt="Screenshot 2023-12-08 at 12 22 58 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/021cd6c8-d650-4a64-813c-759cd3d56e1a">

**Comment by samithaf** [comment]
Possible duplicate of https://github.com/WestpacGEL/GEL-next/issues/476. @catalinacatalina check with @KateMacdonald

**Comment by KateMacdonald** [comment]
@samithaf Fixed
