### ISSUE TITLE
Design System Docs: Related information section - reduce padding between sub-head and text

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#499]
Related information section: Reduce padding between sub-head and text

Old site:
![Uploading Screenshot 2023-12-08 at 12.48.08 pm.png…]()

GEL 4.0:
<img width="920" alt="Screenshot 2023-12-08 at 12 47 55 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/f12fa858-e75d-4b00-b712-5dfb178586cf">

**Comment by samithaf** [comment]
Possible duplicate of https://github.com/WestpacGEL/GEL-next/issues/476 @catalinacatalina please check with @KateMacdonald

**Comment by KateMacdonald** [comment]
@samithaf Not a duplicate, please match existing padding.
