### ISSUE TITLE
Design System Docs: Fonts – Accessibility: Update copy to reflect old site

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#501]
Copy is different on the Accessibility tab. 

Old:
<img width="900" alt="Screenshot 2023-12-08 at 1 16 32 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/c14f752f-609d-4fc3-9a22-cb8d350cafcb">

GEL 4.0:
<img width="909" alt="Screenshot 2023-12-08 at 1 15 19 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/6a7b0b1e-ac94-4344-a614-db0a0ae96ab7">

https://gel-next-site.vercel.app/design-system/foundation/font?brand=wbc&tab=accessibility

**Comment by samithaf** [comment]
@catalinacatalina fixed. Please test again.
