### ISSUE TITLE
Design System Docs: Fonts – Code: "Core package" link goes to 500 internal server error

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#502]
GEL 4.0:
<img width="802" alt="Screenshot 2023-12-08 at 1 19 54 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/72e845f4-489f-4d91-8519-8a515bb4886a">

Clicking "core package" link goes to:
<img width="811" alt="Screenshot 2023-12-08 at 1 18 12 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/c2c9ba31-577d-4c0d-a848-940c42d73a35">

**Comment by KateMacdonald** [comment]
@samithaf Hey Samitha as we talked about, can you please add the Development demos to the pages that used to have Core in them. :)
