### ISSUE TITLE
Design System Docs: Grid - Design: Images are different

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#503]
Grid - Design: All the images are different (this is probably due to an update - and they look good) @KateMacdonald ?

I'm assuming this isn't a fix, but an update? Just logging anyway. 

Old site:
<img width="862" alt="Screenshot 2023-12-08 at 1 25 58 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/f1471079-a797-4059-8f3f-7a30d9a95c55">

GEL 4.0:
<img width="864" alt="Screenshot 2023-12-08 at 1 26 04 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/4f1b0369-efec-4835-a6f5-3bc2420126b8">

https://gel-next-site.vercel.app/design-system/foundation/grid?brand=wbc
https://gel.westpacgroup.com.au/design-system/foundation/grid?b=WBC

**Comment by KateMacdonald** [comment]
@catalinacatalina This is fine I will close.
