### ISSUE TITLE
Design System Grid: Grid - Code: examples not displaying

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#504]
Grid - Code: Transposed / Offset / Areas: examples not displaying and code snippet is missing

<img width="896" alt="Screenshot 2023-12-08 at 1 36 29 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/4cdf5099-9bfc-40c3-8489-8b2a4ae5ceff">

<img width="871" alt="Screenshot 2023-12-08 at 1 38 22 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/57bca2fa-7546-4c78-a02d-46bad90627a7">

https://gel-next-site.vercel.app/design-system/foundation/grid?brand=wbc&tab=code

**Comment by samithaf** [comment]
@catalinacatalina fixed. Please test again.
