### ISSUE TITLE
GEL Design System Docs: Icons - Design: Missing Icons

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#506]
Some icons are missing or different. I suspect this is due to the new icon set? @KateMacdonald 

**CreditCardsIcon**

GEL 4.0: 
<img width="801" alt="Screenshot 2023-12-08 at 1 57 48 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/99d52c3e-d557-4fa3-890b-611e209442c0">

Old:
![Uploading Screenshot 2023-12-08 at 1.57.53 pm.png…]()

ExitIcon different
GEL 4.0:
<img width="811" alt="Screenshot 2023-12-08 at 2 01 23 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/b248b495-ea83-4c02-860c-95e5df10e5f7">

Old:
<img width="862" alt="Screenshot 2023-12-08 at 2 01 03 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/3fd2989a-50a3-4a20-a48f-f074bdfe7c70">

**Comment by KateMacdonald** [comment]
@catalinacatalina This is fine I will close - new icons set.
