### ISSUE TITLE
Design System Docs: Pictograms – Code: Props table missing content

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#516]
Props table in Pictograms is missing lots of content. Confirming with @KateMacdonald if this is a content change?

Old:
<img width="983" alt="Screenshot 2023-12-08 at 8 53 36 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/4b3d2168-4112-4e10-8c63-915d16707e29">

GEL 4.0:
<img width="983" alt="Screenshot 2023-12-08 at 8 53 36 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/7cad2c78-502a-40f6-902b-4de45fb371a8">

https://gel-next-site.vercel.app/design-system/foundation/pictogram?brand=wbc&tab=code
https://gel.westpacgroup.com.au/design-system/foundation/pictograms?b=WBC&tab=code

**Comment by samithaf** [comment]
@catalinacatalina it's not a content change. Development team to fix it.

**Comment by KateMacdonald** [comment]
@catalinacatalina This is fine i will close.
