### ISSUE TITLE
Design System Docs: Text styling - Accessibility: Revise font to be the same as old GEL

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#517]
**Text styling – Accessibility tab:** Replace copy (needs to be the same as old Gel)

**Old:**
![Uploading Screenshot 2023-12-08 at 9.07.43 pm.png…]()

**GEL 4.0:**
<img width="958" alt="Screenshot 2023-12-08 at 9 07 33 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/09625513-08a0-497d-a8f6-588dd24602f4">

https://gel-next-site.vercel.app/design-system/foundation/text-styling?brand=wbc&tab=accessibility
https://gel.westpacgroup.com.au/design-system/foundation/text-styling?b=WBC&tab=accessibility

**Comment by samithaf** [comment]
@catalinacatalina fixed. Please test again.
