### ISSUE TITLE
Design System Docs: Text Styling – Code: Missing content anchor links

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#518]
**Missing anchor links**

Old
<img width="984" alt="Screenshot 2023-12-08 at 9 17 30 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/e21b7294-66d2-485e-b6a6-ed0609665b34">

GEL 4.0
<img width="991" alt="Screenshot 2023-12-08 at 9 17 35 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/42388bee-e345-494b-9d03-f50846170691">

**Comment by samithaf** [comment]
@catalinacatalina old screenshot actually shows new GEL and new screenshot shows old GEL.

**Comment by KateMacdonald** [comment]
@catalinacatalina This is fine I will close.
