### ISSUE TITLE
Design System Docs: Is 'Typography' an intentional nav item? (There is no 'Typography' visible in old Gel)

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#519]
GEL 4.0 has a new nav item "typography" - is this a mistake or intentional? @KateMacdonald 

Old
<img width="751" alt="Screenshot 2023-12-08 at 9 23 05 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/2b65ae09-4c21-4f61-bf15-7c269520d3a6">

GEL 4.0
<img width="754" alt="Screenshot 2023-12-08 at 9 23 11 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/64d0323d-67f2-4df9-a811-a4cb5ef8bb4f">

**Comment by samithaf** [comment]
We need to show typography since it's a design token. Otherwise consumers of GEL wouldn't know the existence of it. cc @KateMacdonald might need your help to add more content in this tab.

**Comment by samithaf** [comment]
@KateMacdonald fixed. We moved the content to font developer docs tab
