### ISSUE TITLE
Design System Docs: A11y (Dev) page content anchor links are repeated

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#520]
Page content: 
<img width="982" alt="Screenshot 2023-12-08 at 9 32 00 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/30bdb813-7b5f-4754-8801-b17a27f61f4f">

https://gel-next-site.vercel.app/design-system/components/a11y?brand=wbc

**Comment by samithaf** [comment]
H3 tags automatically get added to page content in "code" tab. We may need to reorganize content. cc @KateMacdonald

**Comment by KateMacdonald** [comment]
@samithaf Only sections (H2s) should have Page content anchor links.

**Comment by samithaf** [comment]
@kenjishiromajp please see above comment from @KateMacdonald
