### ISSUE TITLE
Design System Docs: Accordions – Design: Copy change

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#521]
Should Tabcordion be Accordion? @KateMacdonald 

<img width="946" alt="Screenshot 2023-12-08 at 9 39 18 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/7324aed0-713c-4bb9-82e2-e0676b2c4326">

https://gel-next-site.vercel.app/design-system/components/accordion?brand=wbc

**Comment by samithaf** [comment]
We need to split tabaccordion to two components (tab and accordion) since it is very confusing for any GEL consumer. We can provide an example of responsive behaviour as an example ( change tab to accordion for mobile breakpoint). cc @KateMacdonald

**Comment by KateMacdonald** [comment]
Fixed and published
