### ISSUE TITLE
Progress rope: Grouped version different to Original GEL

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#529]
**Original GEL**

![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/2871539c-7b3a-4518-84b7-89ee6cdc5b08)

**GEL4**

![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/ceeda6b9-b008-443c-810d-307051e6bb7f)

**Comment by samithaf** [comment]
@KateMacdonald Fix is available in the [latest version](https://gel-next-storybook.vercel.app/?path=/story/components-progressrope--grouping-steps). Can you please check?

**Comment by KateMacdonald** [comment]
Re-tested, looks good
