### ISSUE TITLE
Design system docs: Symbols page wrong Visa symbol

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#534]
Wrong VISA logo - __VisaWhiteSymbol_ looks much bigger
Original GEL
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/41592203-d6f7-4a60-960c-ab381aefe65c)

GEL4
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/7a1891e7-9526-4875-a6a2-3efc4309655f)

**Comment by jaortiz** [comment]
Fixed in #543
