### ISSUE TITLE
Design system docs: Symbols page wrong layout bug

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#535]
The way the symbols are laid out in the white boxes make the labels unaligned - looks a bit messy. All labels should be bottom aligned.

Original GEL
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/595f04fc-2f9c-43ff-b92b-f389c68d17ad)

GEL4
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/c413e2f1-de96-4d8f-8270-bab745f806f1)

**Comment by jaortiz** [comment]
Fixed in #543
