### ISSUE TITLE
New component: Header

### ISSUE THREAD

**Issue by samithaf** [WestpacGEL/GEL-next#550]
We need to create the Header component but will need to check with UX if they want adopt any design in to it.

**Comment by KateMacdonald** [comment]
Headers should use the MultibrandLogo versions. The sizes have been made specifically for that use case. 

Xs uses MultibrandLogoSmall and the rest use MultibrandLogoLarge.

![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/f442066a-44fa-4b72-9a43-c1ce6c5316dd)
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/21bd18c5-8aa3-4f76-b22f-e8ee2693c0e7)
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/7c5ab973-3378-4c9c-8259-44552dea3155)

etc
