### ISSUE TITLE
Design system docs - Descriptio not appearing on code tab pages

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#563]
**Original GEL**
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/0f50cdbf-bfe2-4f83-af0a-0e81a3bd2e9a)

**GEL 4** I can see the copy on the CMS, it's just not appearing on page.
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/cca71bb0-2842-4970-8183-766225dd9a0d)

**Comment by samithaf** [comment]
@KateMacdonald issue is fixed and please check again.
