### ISSUE TITLE
Accordion/Tabs components: Internal styling not being recognised

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#566]
The content inside the Accordion does not seems to to be recognising the styling:
In this example, The _My files_ heading is in an H3 tag. I'm guessing there should be more space between the copy and the button, too.

![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/2c0a3514-e12f-489c-949c-727aa82c6dc2)

**Comment by samithaf** [comment]
@KateMacdonald this is not a bug. We don't assign any styles to HTML H tags. You will need to specify classes `typography-body-8 mb-2`


<img width="1124" alt="Screenshot 2023-12-15 at 11 48 57 am" src="https://github.com/WestpacGEL/GEL-next/assets/1860417/6d8ebacd-6fd2-422d-a312-e07426e2f528">

**Comment by samithaf** [comment]
@KateMacdonald also we need to include a page similar to this in to our docs. https://westpacgel-develop.netlify.app/heading/Heading
