### ISSUE TITLE
Selector Component: Missing a few icon sizes

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#572]
GEL OLD (displaying 6 sizes in total):

<img width="1070" alt="Screen Shot 2023-12-15 at 2 23 30 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/061ed026-8b83-418a-87a5-1a25afbec4db">

<img width="1056" alt="Screen Shot 2023-12-15 at 2 23 38 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/4deff045-17eb-464e-a6fb-ea3ccffc3ef8">

GEL 4: (displaying only 3 sizes) 
<img width="913" alt="Screen Shot 2023-12-15 at 2 25 34 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/e65e4558-f1ae-46cd-99b9-23f5bd307456">

https://westpacgel-develop.netlify.app/selector/icon
https://gel-next-storybook.vercel.app/?path=/story/components-selector--icons-sizes

**Comment by samithaf** [comment]
@catalinacatalina issue is fixed. Please test again.
