### ISSUE TITLE
Selector: Inconsistent application of red chevrons on the "Radio" & "Check with arrow" selector

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#577]
In Storybook it seems there is inconsistency between GEL 4 and Storybook in the way the red chevron has been applied. @KateMacdonald @justinspencer What should the rule be here? Thoughts?

In GEL 3 - It is only **Buttons and Links** that are the only selectors that have the red chevron. Radio buttons have **no chevron**. 

<img width="705" alt="Screen Shot 2023-12-15 at 3 42 25 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/41c57142-a254-46d8-866c-21a689781cda">
https://westpacgel-develop.netlify.app/selector/examples

In Storybook - it seems the way the red chevron has been applied is different. 

1. On Storybook – The radio has a red chevron 
<img width="503" alt="Screen Shot 2023-12-15 at 3 43 57 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/a9d7000a-164a-4baa-a5fe-794081301867">
https://gel-next-storybook.vercel.app/?path=/story/components-selector--radio-with-icons-and-secondary-label

2. On Storybook – Here is a radio with no chevron

<img width="496" alt="Screen Shot 2023-12-15 at 3 44 06 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/2a79e5f9-412d-4c16-ac79-952a261960c8">
https://gel-next-storybook.vercel.app/?path=/story/components-selector--radio-with-state

3. On storybook - “Check with arrow” has a a chevron
<img width="498" alt="Screen Shot 2023-12-15 at 3 44 12 pm" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/e4a4bd7f-ae85-4b27-8be4-5fc961c299f6">
https://gel-next-storybook.vercel.app/?path=/story/components-selector--check-with-arrow

**Comment by samithaf** [comment]
@catalinacatalina issue is fixed. Please test again.
