### ISSUE TITLE
Selector - Icons and secondary label: Demonstrates the variations available of "icons and secondary label" 

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#579]
IN GEL 3 – The example demonstrates the variations available of "icons and secondary label" - Display examples like GEL 3 (This way readers can understand what the differences are)

<img width="1063" alt="Screen Shot 2023-12-18 at 9 28 14 am" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/b3e00ffa-8635-479f-b089-6bd38ad8fcb0">

https://westpacgel-develop.netlify.app/selector/secondary-label
https://gel-next-storybook.vercel.app/?path=/story/components-selector--icons-and-secondary-label

**Comment by samithaf** [comment]
@catalinacatalina issue is fixed. Please test again.
