### ISSUE TITLE
Selector missing the style for “Link” 

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#580]
Missing the selector type for “Link” 

(although it doesn’t seem like this does anything in GEL 3 - as non of the text links anywhere) 

GEL 3
<img width="384" alt="Screen Shot 2023-12-18 at 9 36 11 am" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/aa43dff4-811e-434f-bc8e-5f0410316915">

Storybook

![Uploading Screen Shot 2023-12-18 at 9.36.57 am.png…]()

https://westpacgel-develop.netlify.app/selector/secondary-label
https://gel-next-storybook.vercel.app/?path=/docs/components-selector--docs

**Comment by samithaf** [comment]
@KateMacdonald Do we need the "button" and "link" variation in selector component given that "flexiCell" can be use to achieve a similar outcome? Also looking at the Mesh version, they don't the "link" variation.

**Comment by KateMacdonald** [comment]
@samithaf Yes, we def need the link version. It was the original purpose for this component. It is possible that we might deprecate the whole thing in the future with the Flexicell taking over, but right now there are LOTS of projects using the Selector as it is, and definitely using the link version.

**Comment by samithaf** [comment]
@catalinacatalina issue is fixed. Please test again.
