### ISSUE TITLE
Selector – Radio with icons and secondary label

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#581]
The amount should be positioned to the top (in line with the chevron)  

*Also – I think only Button and Links have the red chevron (see earlier issue)

<img width="1283" alt="Screen Shot 2023-12-18 at 9 41 05 am" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/d9708c62-ff28-4ce6-a08e-711a2c93ff48">

https://gel-next-storybook.vercel.app/?path=/story/components-selector--radio-with-icons-and-secondary-label
https://westpacgel-develop.netlify.app/selector/secondary-label

**Comment by samithaf** [comment]
@catalinacatalina issue is fixed. Please test again.
