### ISSUE TITLE
Missing the style for "Data driven, OnChange, overrides"

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#582]
<img width="1596" alt="Screen Shot 2023-12-18 at 9 44 20 am" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/42541b7f-15e5-4efb-910c-6c7ed378778f">

Storybook
<img width="1582" alt="Screen Shot 2023-12-18 at 9 47 56 am" src="https://github.com/WestpacGEL/GEL-next/assets/77946140/a389983c-b8b5-4d2e-b194-39a10ba8f23f">

**Comment by samithaf** [comment]
@catalinacatalina this is not a bug. GEL 3.0 wasn't showing the underlying code but GEL 4.0 does since we are using storybook. Therefore no need to create all the variations as GEL 3.0 given these docs specially targeting developers.
