### ISSUE TITLE
Content guidelines - Bolding and underlining - CTA link not working 

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#584]
CTA link not working
![Screenshot 2023-12-18 at 12 03 49 pm](https://github.com/WestpacGEL/GEL-next/assets/77946140/d7ecbd9b-9eaa-42c4-9666-ccfab9f2b5e3)

https://gel-next-site.vercel.app/design-system/content/guidelines/bolding-underlining?brand=wbc

**Comment by KateMacdonald** [comment]
Fixed in branch content-kate-dev
