### ISSUE TITLE
Content guidelines - Calls to action (CTAs): phone number is missing underline

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#585]
Add an underline on the phone number

OLD:
![Uploading Screenshot 2023-12-18 at 12.10.50 pm.png…]()

GEL 4:
![Screenshot 2023-12-18 at 12 10 55 pm](https://github.com/WestpacGEL/GEL-next/assets/77946140/96382f69-1c11-492e-8cb3-9e011129bd94)

**Comment by KateMacdonald** [comment]
Fixed in branch content-kate-dev
