### ISSUE TITLE
Content guidelines - Capital letters: Links not working and some words need to be underlined

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#586]
Add a url for the following links:

- Headings and subheadings (Headings section)
- Compare accounts and what's new (Sentence-case section)
- People and diversity (Capitalisation section)

![Screenshot 2023-12-18 at 12 16 29 pm](https://github.com/WestpacGEL/GEL-next/assets/77946140/992b8849-90a4-43f8-a201-35060e033d13)
OLD:
![Screenshot 2023-12-18 at 12 16 33 pm](https://github.com/WestpacGEL/GEL-next/assets/77946140/d4f8a00e-93c7-4f07-ba7f-3dc35721d98f)

![Screenshot 2023-12-18 at 12 17 55 pm](https://github.com/WestpacGEL/GEL-next/assets/77946140/3182e567-5175-4980-bf1b-a8592ce660b9)

![Screenshot 2023-12-18 at 12 15 53 pm](https://github.com/WestpacGEL/GEL-next/assets/77946140/8c5de426-c49b-46f3-a16e-af559ef8e874)

https://gel-next-site.vercel.app/design-system/content/guidelines/capital-letter?brand=wbc

**Comment by KateMacdonald** [comment]
Fixed in kates branch
