### ISSUE TITLE
Content guidelines - Days, date, time: Double space 

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#587]
Add a space between: 
"Note: For 12am and 12pm, use ‘midnight’ and ‘noon’." 

and

"For example:"

![Screenshot 2023-12-18 at 12 25 53 pm](https://github.com/WestpacGEL/GEL-next/assets/77946140/519afc46-c407-426a-810e-6529ea1a539b)

OLD:
![Screenshot 2023-12-18 at 12 25 57 pm](https://github.com/WestpacGEL/GEL-next/assets/77946140/400e55af-1805-4460-bb17-792403a65e1b)

https://gel-next-site.vercel.app/design-system/content/guidelines/dates-days-time?brand=wbc

**Comment by KateMacdonald** [comment]
Fixed in kates branch
