### ISSUE TITLE
Content guidelines - Hyperlinks & email addresses: Add a space between some text

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#588]
Add a space here:

![Screenshot 2023-12-18 at 12 37 13 pm](https://github.com/WestpacGEL/GEL-next/assets/77946140/373ae8e7-629f-45c1-a7ac-7a0a5e6ba891)

OLD
![Screenshot 2023-12-18 at 12 37 19 pm](https://github.com/WestpacGEL/GEL-next/assets/77946140/01ac520c-648e-44cd-96b6-cbe17b6a6deb)

https://gel-next-site.vercel.app/design-system/content/guidelines/hyperlinks-email-addresses?brand=wbc

**Comment by KateMacdonald** [comment]
Fixed in kates branch
