### ISSUE TITLE
Content Guidelines – Hyperlinks and email addresses: underline some words

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#589]
Underline the following words:

![Screenshot 2023-12-18 at 12 37 13 pm](https://github.com/WestpacGEL/GEL-next/assets/77946140/2669dd5d-608a-42bd-95bb-e6e5b4a642b2)

OLD
![Screenshot 2023-12-18 at 12 37 19 pm](https://github.com/WestpacGEL/GEL-next/assets/77946140/79540dcc-c851-4bec-ab91-03d12f264e87)

Also: the atolink should be underlined:

![Screenshot 2023-12-18 at 12 42 11 pm](https://github.com/WestpacGEL/GEL-next/assets/77946140/38a80c52-7b7d-4764-8527-b611e11de45d)

https://gel-next-site.vercel.app/design-system/content/guidelines/hyperlinks-email-addresses?brand=wbc

**Comment by KateMacdonald** [comment]
Fixed in kates branch
