### ISSUE TITLE
Content Guidelines - People & diversity: Accessibility GEL Principles link goes to blank page 

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#590]
![Screenshot 2023-12-18 at 12 49 40 pm](https://github.com/WestpacGEL/GEL-next/assets/77946140/2b8ae1a1-a519-458f-a0e6-febcf4894b4c)

https://gel-next-site.vercel.app/design-system/content/guidelines/people-diversity?brand=wbc

**Comment by KateMacdonald** [comment]
Fixed in content-kate-dev branch

**Comment by KateMacdonald** [comment]
Fixed in kates branch
