### ISSUE TITLE
Content Guidelines – Punctuation & symbols: Add some underlines

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#591]
![Screenshot 2023-12-18 at 12 58 31 pm](https://github.com/WestpacGEL/GEL-next/assets/77946140/4f711396-ef0b-400f-b78a-3666fdf2930a)

OLD:
![Screenshot 2023-12-18 at 12 59 51 pm](https://github.com/WestpacGEL/GEL-next/assets/77946140/0f7477d3-da12-467a-9760-95e117fa08ee)

https://gel-next-site.vercel.app/design-system/content/guidelines/punctuation-symbol?brand=wbc

**Comment by KateMacdonald** [comment]
Fixed in kates branch
