### ISSUE TITLE
Content Guidelines – Superscripts & Trademarks: Add an underline

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#592]
Add an underline and remove italic style – "eStatements"

![Screenshot 2023-12-18 at 1 05 07 pm](https://github.com/WestpacGEL/GEL-next/assets/77946140/b5e9f2ab-d991-4859-81ce-66b1a842a86f)

OLD
![Screenshot 2023-12-18 at 1 05 14 pm](https://github.com/WestpacGEL/GEL-next/assets/77946140/8049e5c1-9ac2-4a87-b21e-4873e42c8254)

https://gel-next-site.vercel.app/design-system/content/guidelines/superscripts-trademarks?brand=wbc

**Comment by KateMacdonald** [comment]
Fixed in kates branch
