### ISSUE TITLE
Content Guidelines – Third party websites: Add some underlines

### ISSUE THREAD

**Issue by catalinacatalina** [WestpacGEL/GEL-next#593]
Add some underlines for "myTax", "myGov"

![Screenshot 2023-12-18 at 1 07 15 pm](https://github.com/WestpacGEL/GEL-next/assets/77946140/cd6321cb-4872-4759-8b0c-4df739768719)

OLD
![Screenshot 2023-12-18 at 1 07 18 pm](https://github.com/WestpacGEL/GEL-next/assets/77946140/53b4374c-60a2-4199-acff-1d319d7d9500)

https://gel-next-site.vercel.app/design-system/content/guidelines/third-party-websites?brand=wbc

**Comment by KateMacdonald** [comment]
Fixed in content-kate-dev branch
