### ISSUE TITLE
Add underlining as option for site CMS

### ISSUE THREAD

**Issue by tomjackking** [WestpacGEL/GEL-next#595]

**Comment by KateMacdonald** [comment]
@tomjackking, is this to support the content issues around, needing underlines eg #593 ? Because i think we can sort these out with dummy hyperlinks.

**Comment by tomjackking** [comment]
Yes, but I don't think using dummy hyperlinks will work because of styling that we have on links. I should be able to add underlining as an option without too much hassle

**Comment by samithaf** [comment]
Fixed. @KateMacdonald change is now available.
