### ISSUE TITLE
Inputs (Autocomplete, Text input, Select etc) - Way to determine fixed width

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#598]
We used to have a fixed width option in GEL3, need to discuss best way to implement:

![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/dd329ac5-ad48-471d-ab60-109f2124bddc)

Components effected:

- Text input
- Textarea
- Autocomplete
- Select
- Input group
- Input field

**Comment by samithaf** [comment]
@KateMacdonald need more information and this can be easily done via a parent wrapper element as well.
