### ISSUE TITLE
Progress indicator - can we rename this to something like Loading indicator or loader

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#682]
Progress indicator - can we rename this to something like Loading indicator or loader?

**Comment by samithaf** [comment]
@KateMacdonald for sure we can. However we named component to align with probably the largest design systems in the world.

https://m3.material.io/components/progress-indicators/
https://developer.apple.com/design/human-interface-guidelines/progress-indicators
