### ISSUE TITLE
Design system docs: Allow for pages to exist but not appear in nav 

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#683]
Is there a way to be able to create a page without it immediately appearing in the nav?

**Comment by samithaf** [comment]
@JedWatson is there a way to create pages only visible for site admins/editors? We can add a custom prop in the Keystatic and achieve what @KateMacdonald wants but keen to know if this capability exists within Keystatic.

<img width="344" alt="Screenshot 2024-01-25 at 1 35 02 pm" src="https://github.com/WestpacGEL/GEL-next/assets/1860417/b696f0b5-877d-48a9-9145-2980313f599d">
