### ISSUE TITLE
Badges - additional colour options

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#691]
New colour/style options added to the Badges component. 

- [x] Reduce the font weight of the ‘Pill’ style badge from 700 to 500
- [x] Update the colour of the ‘Faint’ badge styles  - see specifications.
- [x] Create a ’soft’ colour variation for all Badge styles, white fills with borders - see specifications.

Figma file with specifications
https://www.figma.com/file/vzWEj46dsPJevhBkSAgOyU/Badges---New-colours?type=design&node-id=0%3A1&mode=design&t=4DBu3otDrotG2AZK-1

Happy to discuss when requied.

**Comment by KateMacdonald** [comment]
@jaortiz Hey Jeremy, just want to add to this that the soft style badges are different to the 'inverted style' used inside buttons, as they have borders.

**Comment by jaortiz** [comment]
Added in #700
