### ISSUE TITLE
New icon - Piggy Bank

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#707]
Please add the new Piggy Bank icon to the library. I've attached SVG's for the filled and outlined styles.

![piggy-bank-filled](https://github.com/WestpacGEL/GEL-next/assets/936597/c422a3dd-e005-4e56-8267-6b250756199a)
![piggy-bank-outlined](https://github.com/WestpacGEL/GEL-next/assets/936597/96db0b00-1009-447c-843d-76cef9adaff4)

**Comment by KateMacdonald** [comment]
@samithaf This issue was closed, however the icon is not visible in the GEL library.

**Comment by HZ991** [comment]
included in #941
