### ISSUE TITLE
Bottom-sheet and Modal - Visual update

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#714]
Visual update to both the Modal and the Modal state of the Bottom sheet.

Here is a link tot he Figma file, happy to discuss when ready: https://www.figma.com/file/WbAVpii2p7KDQYu1TPboyn/Modular-banking---Library-%26-Components-WIP?type=design&node-id=1721%3A8557&mode=design&t=tVEOMAUcoCJJQxGK-1

**Comment by samithaf** [comment]
Please update the design and group with breakpoints.

**Comment by KateMacdonald** [comment]
@tomjackking Modal and Bottom sheet look great. Is it possible for the Modal to be vertically centred to match the Bottom-sheet?

**Comment by KateMacdonald** [comment]
@tomjackking Hey Tom, I just noticed that the Modal component is using the same Westpac brand colours for all other brands.

**Comment by tomjackking** [comment]
> @tomjackking Hey Tom, I just noticed that the Modal component is using the same Westpac brand colours for all other brands.

This has been moved to #740
