### ISSUE TITLE
Autocomplete error state

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#715]
Should the error state for the autocomplete component have the input outlined in red as per the other inputs? https://gel-next-storybook.vercel.app/?path=/story/components-autocomplete--error-message-and-label

![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/e76bf31f-03a4-4c81-8da2-970d99dd3e12)

**Comment by samithaf** [comment]
Not a bug but storybook demo is missing following prop.
`invalid`
