### ISSUE TITLE
2 new icons

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#720]
Please add the attached icons to the library.

child-care
child

Optimised SVG's for both filled and outlined versions are attached.

[svgs.zip](https://github.com/WestpacGEL/GEL-next/files/14274937/svgs.zip)

**Comment by tomjackking** [comment]
@justinspencer it looks like the child icons are the same, the other icons look fine though. Could you confirm and send through the correct child icons if one is incorrect?

**Comment by tomjackking** [comment]
Have confirmed with Justin the icons should be the same

**Comment by KateMacdonald** [comment]
@samithaf This issue was closed, however these icons are not visible in the GEL library.
