### ISSUE TITLE
Remove twitter and add X icon.

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#727]
Please remove the twitter icon and add the X icon. I've attached svg's for both filled and outlined icons.
I've also attached 3 versions of the X mark which are intended to go into the Symbols.

[X.zip](https://github.com/WestpacGEL/GEL-next/files/14391704/X.zip)

**Comment by KateMacdonald** [comment]
@samithaf This issue was closed, however the icon change is not visible in the GEL library.
