### ISSUE TITLE
Ability to hide Demo link

### ISSUE THREAD

**Issue by samithaf** [WestpacGEL/GEL-next#737]
I think in some places we don't need "Demo" button which shows the example in full screen modal. I wonder we need a way to disable this button via cms for certain examples. @KateMacdonald thoughts?

![Screenshot 2024-02-22 at 9 07 42 pm](https://github.com/WestpacGEL/GEL-next/assets/1860417/9714e0cb-c9b5-4af8-a771-ec6ec062a542)

**Comment by KateMacdonald** [comment]
@samithaf 100% agree! -This is so funny, I was coming in to Github to request this myself. I did ask Kenji about it a while ago, but it doesn't appear to be straight forward unfortunately.

**Comment by HZ991** [comment]
issue resolved with following PR
#859 - added cms option to turn off Demo button for design demos
#852 - made a separate component for content platform availability to allow the availability of component to be updated in cms
