### ISSUE TITLE
Re-add the old twitter icon

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#768]
Please re-add the twitter icon. This is to align with the ION library and the Android webfont. Filled and Outlined SVG's are in the attached zip file.

[twitter-icon.zip](https://github.com/WestpacGEL/GEL-next/files/14878839/twitter-icon.zip)

**Comment by jaortiz** [comment]
https://gel-next-storybook.vercel.app/?path=/docs/foundation-icons--docs
