### ISSUE TITLE
New Icons - drop-right and drop-left

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#784]
We've added additional directions (left and right) to the drop arrow (see screen grab attached).
This is for filtering content in tables etc.
I've attached SVG's for both states (although they are identical).

![Screenshot 2024-05-09 at 1 07 06 PM](https://github.com/WestpacGEL/GEL-next/assets/936597/02cc8c2d-553f-4afe-87ae-937dec27280e)

Here are the SVG's
[drop arrows.zip](https://github.com/WestpacGEL/GEL-next/files/15257224/drop.arrows.zip)

**Comment by HZ991** [comment]
I will begin working on this issue, commenting to allow self-assignment
