### ISSUE TITLE
Default Badges - Text position

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#787]
The text position in the default badge is not correct. It should be vertically (optically) centred. I've had a look at the CSS and I think I've found a solution:

Use the "normal" value in the line-height property.

**However... only do this for the Default Badge as the normal value seems to break all the other components.**

I've tested this in Chrome and Safari (Mac) and it looks like it works. I've attached screen grabs showing the 2 versions.

<img width="1408" alt="01-incorrect" src="https://github.com/WestpacGEL/GEL-next/assets/936597/e62619fa-5528-4ffb-a9d1-60db6f572010">

<img width="1408" alt="02-correct" src="https://github.com/WestpacGEL/GEL-next/assets/936597/2af92e5b-f3f5-456a-8973-54afa002dc60">

**Comment by tomjackking** [comment]
@justinspencer this is how it looks on Windows Chrome when setting line height to normal: 
![image](https://github.com/WestpacGEL/GEL-next/assets/46306101/f36ca114-0c93-48b0-8092-2bd659d92536)
This looks like the text is too low to me.

**Comment by justinspencer** [comment]
@tomjackking Yep you're right. Looks like we'll have to increase the size of the Default label to 20px. This would make them exactly the same as the Github badges which seem to work.

**Comment by KateMacdonald** [comment]
@tomjackking Hey Tom, while you're in there, we also need to update the label colour of the Faint badge styles to be Text (Muted wasn't accessible).

**New colours**
Faint style colours:
Fill=Border
Label=Text

Faint soft style colours:
Fill=White
Border=Border
Label=Text

**Comment by tomjackking** [comment]
This has been merged to develop. For documentation purposes we found in a discussion that the difference in the badge visually between Windows and Mac was because of the Windows font Segoe UI not centring itself. We decided to go with an option that looks visually good on Mac and acceptable on Windows.
