### ISSUE TITLE
Adding arrows to filter component (accessibility uplift)

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#792]
To make this component accessible, we need to add arrows that move the 'chips' along.

 would also like a version of the filter that doesn't come with the search box.

![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/47541b5b-a6c9-494f-8632-873f4f42561e)

**Comment by samithaf** [comment]
@HZ991 would you be able to help?

**Comment by HZ991** [comment]
I would like to participate in this issue
