### ISSUE TITLE
Error message alignment

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#844]
The error messages that appear with fields are not aligning with the alert icons properly. they should be aligned with top of the text when there are multiple lines, they are currently vertically centering.

Looks like this:
![image](https://github.com/user-attachments/assets/797273f9-159d-443f-aa00-c1d8c6753802)

Should look like this:
![image](https://github.com/user-attachments/assets/d679c456-32d3-4d67-8fa7-7d317e29d508)

**Comment by HZ991** [comment]
closed in #861
