### ISSUE TITLE
Update to Alert component (icon sizes)

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacGEL/GEL-next#851]
Can we add size variant to the Text mode version of the Alert component: https://gel-next-storybook.vercel.app/?path=/story/components-alert--text-mode

We need it to allow Sm (12px), Md (18px) and Lg 24px icon options.

So default would be the version with responsive 18px-24px icons.

**Comment by jaortiz** [comment]
@HZ991 Can you add a changeset for this change

**Comment by HZ991** [comment]
resolved in #866 and #867
