### ISSUE TITLE
BT Brand Theme - Assets

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#923]
These are the mapped colours for the new BT Brand.

Background: #F5F5F5
Border: #D9D9D9
Heading: #171717
Hero: #00345A
Light: #F9F9F9
Link: #006DBC
Muted: #666666
Neutral: #2A2E42
Pop: #672993
Pop Light: #F7F4FA
Primary: #006DBC
Text: #171717
BorderDark; #949494
Focus: #B470D7

Pictogram Dark: Hero
Pictogram Duo: Hero, Primary
Pictogram Light: White

I've attached:
1. SVG's for all logo variations.
2. PNG showing the above colour mapping
3. PNG showing BT and BT Panorama multi-brand logos.

Please add the logos to the current Logos.
https://gel-next-storybook.vercel.app/?path=/story/foundation-symbols--all-logos

 
[BT Logos.zip](https://github.com/user-attachments/files/17614436/BT.Logos.zip)

<img width="1093" alt="BT-Palette" src="https://github.com/user-attachments/assets/afa56a70-de21-44fb-8f10-414c91043900">

<img width="1439" alt="Logo-headers" src="https://github.com/user-attachments/assets/20132029-6387-4d63-9f4a-700980a638a4">

**Comment by tonytwong** [comment]
@jaortiz please let us know when you have released a gel-next theme for Panorama. We are proposing BTPL as the brand key on ui-components side

**Comment by jaortiz** [comment]
Closed in #924
